<a href="https://colab.research.google.com/github/kanedc/Learning_Pytorch/blob/main/k_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# start


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [1]:
import torch
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
#获得张量的维度数
scalar.ndim

0

In [5]:
#将张量作为Python整型返回
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([5,5])
vector


tensor([5, 5])

In [ ]:
vector.ndim

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[2,3],[4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [13]:
#tensor
TENSOR = torch.tensor([[[1,2,3],[1,2,3],[7,7,7]],[[3,6,3],[1,3,5],[7,7,7]]])
TENSOR

tensor([[[1, 2, 3],
         [1, 2, 3],
         [7, 7, 7]],

        [[3, 6, 3],
         [1, 3, 5],
         [7, 7, 7]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

#Random tensor
 **why random tensor ?**


随机张量很重要，因为许多神经网络的学习方式是从充满随机数的张量开始，然后调整这些随机数以更好地表示数据。

`从随机数开始---》看数据 ---》更新随机数---》看数据 ---》更新随机数`



In [20]:
#创建一个大小为（3,4）的随机张量
random_tensor = torch.rand(1,10,10)
random_tensor

tensor([[[0.9536, 0.2180, 0.4545, 0.8545, 0.3221, 0.0578, 0.7255, 0.2077,
          0.3599, 0.2573],
         [0.7499, 0.3247, 0.8544, 0.0298, 0.4602, 0.9187, 0.2480, 0.0106,
          0.2011, 0.2013],
         [0.1623, 0.0590, 0.1969, 0.2847, 0.0700, 0.0549, 0.5393, 0.3461,
          0.9652, 0.2054],
         [0.7365, 0.4379, 0.4485, 0.0436, 0.8243, 0.6125, 0.7355, 0.9512,
          0.0984, 0.0493],
         [0.3111, 0.0723, 0.8025, 0.4744, 0.5287, 0.1283, 0.1217, 0.8845,
          0.5658, 0.8694],
         [0.7076, 0.2247, 0.0273, 0.9675, 0.5454, 0.0966, 0.9508, 0.2830,
          0.9651, 0.5441],
         [0.2291, 0.2732, 0.4838, 0.4494, 0.6076, 0.3569, 0.2699, 0.1242,
          0.3464, 0.4927],
         [0.2971, 0.5077, 0.7410, 0.1708, 0.3518, 0.2853, 0.4798, 0.3519,
          0.4560, 0.6251],
         [0.5208, 0.0450, 0.7836, 0.6488, 0.8849, 0.4057, 0.5688, 0.3325,
          0.3654, 0.9277],
         [0.4909, 0.6721, 0.8071, 0.3322, 0.9833, 0.4825, 0.1844, 0.6861,
          0.1829,

In [18]:
random_tensor.ndim

3

In [19]:
random_tensor.shape

torch.Size([1, 3, 4])